name: state_machine
version: 2.2.0
description: Finite state machine library. Easily define legal state transitions.
    Listen to state entrances, departures, and transitions.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/state_machine

environment:
    sdk: '>=2.4.0 <3.0.0'

dependencies:
    w_common:
        git:
            url: git@github.com:Workiva/w_common.git
            ref: flutter-fix

dev_dependencies:
    build_runner: ^1.7.1
    build_test: ^2.0.0
    build_web_compilers: ^2.5.1
    build_vm_compilers: ^1.0.3
    dart_dev:
      git:
        url: git@github.com:hunterbreathat-wk/dart_dev.git
        ref: flutter-fix
    dart_style: ^1.3.1
    test: ^1.9.1

dependency_overrides:
  build: ^1.0.0